RUNES: Let mappers dictate rune spawns.
QW-Group/ktx pull request #241
Opened 2022-08-27 20:13 UTC by dsvensson

More than once there has been discussions on rune spawns and how they
randomly might give one of the teams an upper hand.

This feature gives mappers the ability to integrate rune spawn positions
into the map design that will be used whenever a rune (re)spawns.

Dropping a rune still drops it on the ground, but if not picked up, the
regular timeout will cause the rune to respawn at a dedicated position if
such a position is available.

2022-08-28 22:15 UTC, tcsabina requested changes

2022-08-28 22:15 UTC, tcsabina commented on src/runes.c
> +	if (!pos)
Do (pos != NULL) please.
pos is not a boolean, so we should check against NULL

2022-08-28 22:15 UTC, tcsabina commented on src/runes.c
> +		item->s.v.movetype = MOVETYPE_TOSS;
Could you move this to line 42? There we assign 'self' to 'pos'. Is that the only possibility for 'self' be equal to 'pos'?

2022-08-29 07:17 UTC, dsvensson commented
@qqshka made a good point on discord that there's really no reason to limit this to one spawn per rune. Even if my idea was to have kind of like rune altars, who am I to limit the fantasy of mappers. I'll use randomized select spawn instead, and fix your comments as well.

2022-09-05 20:31 UTC, merged