CTF: CRHook fixes & Improvements
QW-Group/ktx pull request #277
Opened 2022-11-24 20:34 UTC by inf1niti

This PR cleans up some issues with the existing `crhook` (fast hook) implementation and is based on community discussion & player feedback provided in the QWCTF discord -> [see conversation here](https://discord.com/channels/778331251332743209/966951245627666482/1044917373859266610)

* adds "cancel time" of 0.5s to initial throw (no spam)
* reduce grapple velocity from 1200 to 1050
* increase pull velocity from 800 to 825
* add linear accel/decel to hook velocity changes (no immediate speed change)
* remove annoying looped grapple sounds for simpler axe swish(throw) and axe hit (anchor) sounds

2022-11-24 21:53 UTC, tcsabina requested changes
~Could you please add a short 'changelog' as well? So we can add it to the release notes when this is published.~
upps, haven't seen your initial comment ;)

2022-11-24 21:53 UTC, tcsabina commented on src/grapple.c
> +	return speed < (800 - incr) ? speed += incr : 800;
please make this human readable :D.

```
float retVal = 800;

if (speed < (800 - incr))
{
  retVal = speed + incr;
}

return retVal;
```

or
```
float retVal = speed + incr;
if (retVal > 800)
{
  retVal = 800;
}
```

2022-11-24 21:53 UTC, tcsabina commented on src/grapple.c
> +	return speed > (800 + decr) ? speed -= decr : 800;
same here. these one liners are super-geek, but it is hard to process them quickly...

2022-11-24 21:53 UTC, tcsabina commented on src/grapple.c
> +		if (owner->hook_cancel_time > 38) {
code style: opening bracket to the new line, please

2022-11-24 21:53 UTC, tcsabina commented on src/grapple.c
> +void CancelCheck(gedict_t *owner) {
code style: opening bracket to do new line, please

2022-11-24 22:43 UTC, inf1niti commented
thanks @tcsabina, adjusted the code as requested.   Would like to get some review from @dsvensson and ideally some testing from the QWCTF group prior to merging this as well.

2022-11-24 22:47 UTC, tcsabina requested changes

2022-11-24 22:47 UTC, tcsabina commented on src/grapple.c
> +	if (speed < (800 - increment))
code style:
please tag the function with some newlines:
- after the variable definitions/declarations
- after a block (closing bracket of an if statement)

2022-11-24 22:47 UTC, tcsabina commented on src/grapple.c
> +	if (speed > (800 + decrement))
same here: please add some newlines as suggested above

2022-11-24 22:47 UTC, tcsabina commented on src/grapple.c
> +	if(cvar("k_ctf_cr_hook"))
code style: extra space between if an opening parenthesis

2022-11-24 22:50 UTC, tcsabina commented
We can probably can summon dsvenson (aka nano from discord), but how do you see the testing?
As the changes only affect the CTF/grapling hook code, I am not afraid to merge it into master, to create a testable snapshot. What do you think? I think that would be easier for a CTF server admin: just get the latest snapshot and update a few server port.

2022-11-24 22:57 UTC, dsvensson commented
You could also change the default of k_ctf_rune_power_hst from 2 to 1.25. I think that was an incorrect port from PureCTF Pro (which has 1.25) when it got added. I'll read up on the changes tomorrow.

2022-11-25 09:27 UTC, tcsabina commented
ok lads. let me know when to merge!

2022-11-25 09:50 UTC, dsvensson commented on src/grapple.c
> +		VectorScale(hookVelocity, self->grapple_vel * 1.125,
This takes a step away from traditional haste settings. PureCTF lineage of CTF defaulted to hst power 1.25, thus player moved at maxspeed * 1.25, as well as hook movement * 1.25, and shooting speed * 1.25.

2022-12-13 17:14 UTC, dsvensson commented
It's still work in progress. Been doing a mini tournament in the CTF corner that has delayed this a bit. Hope to get some additional testing this week, but game feel is very close to finished imho. Lots of people like the changes. Just minor comments here and there. Hasn't stirred up any huge controversies other than a debatable delay.

2022-12-14 17:17 UTC, inf1niti commented
@tcsabina @dsvensson this has been updated.  I've added some new voting logic, so feel free to 🔍 & make suggestions as necessary. 👍 

there is one KTX config change that needs to be propagated when this merges:
**k_ctf_cr_hook:** `0 || 1 (default)` 
becomes 
**k_ctf_hookstyle:** `1 (default) || 2 || 3`

Let me know where/when is best to do that (nquake server?)

2022-12-14 17:24 UTC, tcsabina approved these changes

2022-12-14 17:31 UTC, tcsabina commented
@inf1niti 

Could you explain the 3 versions of k_ctf_hookstyle? I would add it to the Release Notes.

And I think you are right about nquakesv: we should tell those guys to update the stuff whenever KTX 1.43 is released.

2022-12-14 17:58 UTC, inf1niti commented
> Could you explain the 3 versions of k_ctf_hookstyle? I would add it to the Release Notes.

the `k_ctf_hookstyle` cvar lets players decide between three styles of grappling hook: 

## `k_ctf_hookstyle 1`: smooth hook (default) 
The smooth hook implements some new features to help balance CTF gameplay  
  * throw speed has been reduced from cr_hook (1200 -> 1050), while still being faster than the classic hook (800)  
  * player acceleration from the hook pull runs through an easing function, giving the hook an overall "smoother" feel
  * implements a fire delay, limiting "hook spam" approach, encouraging more common movement mechanics (bhop).
  * the hook throw is cancelable, after a short delay.
  
## `k_ctf_hookstyle 2`: fast hook
the fast hook is closest to the existing cr_hook implementation, but the speed has been reduced based on community feedback
  * uses the same speed settings as smooth hook, but does not use hook acceleration, or fire delay.
  * the hook throw is immediately cancelable.
  
## `k_ctf_hookstyle 3`: **classic hook** 
the classic hook uses the original 3wave settings
  * hook throw speed is slower (800)
  * no acceleration / easing function to hook pull
  * a hook throw cannot be canceled until the grapple hits a surface

2022-12-14 19:13 UTC, tcsabina commented
> > Could you explain the 3 versions of k_ctf_hookstyle? I would add it to the Release Notes.
> 
> the `k_ctf_hookstyle` cvar lets players decide between three styles of grappling hook.
> ## `k_ctf_hookstyle 1`: smooth hook (default)
> 
> _votable with `hook_smooth`, 51% player vote threshold required_
> 
> The smooth hook implements some new features to help balance CTF gameplay
> 
>     * throw speed has been reduced from cr_hook (1200 -> 1050), while still being faster than the classic hook (800)
> 
>     * player acceleration from the hook pull runs through an easing function, giving the hook an overall "smoother" feel
> 
>     * implements a fire delay, limiting "hook spam" approach, encouraging more common movement mechanics (bhop)
> 
>     * the hook throw is cancelable, after a short delay
> 
> 
> ## `k_ctf_hookstyle 2`: fast hook
> 
> _votable with `hook_fast`, 51% player vote threshold required_
> 
> the fast hook is closest to the existing cr_hook implementation, but the speed has been reduced based on community feedback
> 
>     * uses the same speed settings as smooth hook
> 
>     * no hook pull acceleration/easing, or fire delay
> 
>     * the hook throw is immediately cancelable
> 
> 
> ## `k_ctf_hookstyle 3`: **classic hook**
> 
> _votable with `hook_classic`, 51% player vote threshold required_
> 
> the classic hook uses the original 3wave settings
> 
>     * hook throw speed is slower (800)
> 
>     * no hook pull acceleration/easing, or fire delay
> 
>     * a hook throw cannot be canceled until the grapple hits a surface

Perfect!

2022-12-14 19:13 UTC, merged

2022-12-16 19:26 UTC, mushis commented
I would like to see more information (description) when chooseing hook mode.
the description of the different hook modes should have more info. example:
`hook_smooth -> "reduced throw speed, with fire delay and acceleration"`

2022-12-16 21:42 UTC, tcsabina commented
> I would like to see more information (description) when chooseing hook mode. the description of the different hook modes should have more info. example: `hook_smooth -> "normal throw speed, with fire delay and acceleration"` `hook_classic -> "slower throw speed, no accel, not cancellable"` `hook_fast -> "normal throw speed, no accel, no delay"`

So read to comment from inf1niti above ;)

2022-12-19 11:50 UTC, mushis commented
> So read to comment from inf1niti above ;)

I meant in the game =) 
as a description of the commands.