RUNES: Randomized rune spawns.
QW-Group/ktx pull request #288
Opened 2023-01-27 17:35 UTC by dsvensson

Runes spawn at either designated `item_rune_$name` spawn points, or `info_player_deathmatch`, and usually there aren't that many to pick from which results in a fairly high probability that multiple runes spawn at the same spawn point, and worst case this spawn point is on the way between base and quad at map start.

This PR introduces unique spawn point selection at match start for runes, and secondly also ports the PureCTF functionality of bouncing runes which further improves the randomization by causing runes to sometimes bounce down ledges etc.

2023-01-28 09:15 UTC, dsvensson commented on src/runes.c
> +		movetype = (int) cvar("k_ctf_rune_bounce") & 1 ? MOVETYPE_BOUNCE : MOVETYPE_TOSS;
https://github.com/qw-ctf/purectf/blob/main/pureitem.qc#L51-L54

2023-01-28 09:20 UTC, dsvensson commented on src/runes.c
> +	item->s.v.movetype = (int) cvar("k_ctf_rune_bounce") & 2 ? MOVETYPE_BOUNCE : MOVETYPE_TOSS;
https://github.com/qw-ctf/purectf/blob/main/items.qc#L1804

2023-01-30 21:19 UTC, tcsabina requested changes

2023-01-30 21:19 UTC, tcsabina commented on src/runes.c
> +gedict_t* SelectSpawnPoint();
I think we don't need this.
The prototype of `SelectSpawnPoint()` is already in g_local.h, which is included in this file.
But in any case, the proper function definition is `gedict_t* SelectSpawnPoint(char *spawnname);`

2023-01-30 21:19 UTC, tcsabina commented on src/runes.c
> +			if (self == runes[i])
I would safeguard any pointer dereferencing with a not-null check.

2023-01-30 21:20 UTC, tcsabina commented
Nano,
please add a short description about this new "k_ctf_rune_bounce" variable. It can have 2 values, right?

2023-01-30 22:46 UTC, dsvensson commented
Three variants: just on spawn, just on toss, or both.

An alternative would be to skip the config variable and add it as a feature request later on.

2023-01-30 22:54 UTC, dsvensson commented on src/runes.c
> +    return self;
oops indentation.

2023-01-31 19:47 UTC, merged