Additional ents
QW-Group/ktx pull request #294
Opened 2023-03-22 21:33 UTC by dsvensson

This brings along the complete set of entities used in the RCTF maps by infiniti. All of them widely available and used in the SP mapping community, nothing too fringe.

2023-03-26 20:57 UTC, tcsabina commented
Nano,

What part of this changeset would you like to see in qwprot?

2023-03-26 21:14 UTC, tcsabina commented
Ignore previous comment, please. It made no sense ;)

2023-03-26 21:30 UTC, dsvensson commented
Here are the RCTF maps, https://bit.ly/rctf_b2 .. rctf3_b2 currently doesn't load in ezQ due to a bug, and func_laser on rctf1_b2 without mvdsv/ezq alpha is a bit boring, but could verify all of this in fteqw-sv + fteqw. Waiting for feedback from infinity as well for this branch but it looks like it's working as intended. They are all very mechanical line-by-line ports from QuakeC to the KTX helper functions.

2023-03-26 21:55 UTC, tcsabina commented
@inf1niti 
let us know when ready to merge.

2023-07-14 06:03 UTC, inf1niti commented
Finally tested this 😅, generally looks good.

Couple of small things:
1. I wasn't able to test the `trigger_heal`, but I assume it works.
2. sounds ref'd from `ambient_general` and other ents (ie. `func_laser`) were not playing for me.  Got these warnings in the console (maybe I've got my sounds in the wrong folder or something?) <img src="https://github.com/QW-Group/ktx/assets/67801374/87020460-322d-4e39-a125-0a026f8eb3ca" width=360 />
3. Was getting console-ddos'd with alpha-related error spam when running rctf1.. This is due to entities with alpha transparency being embedded in the map, and not directly related to this PR **but worth noting anyway, that any map that includes the alpha property on a bmodel will spam players unendingly with the following message: <img src="https://github.com/QW-Group/ktx/assets/67801374/3b1b1419-dc23-44d5-be67-1298ed3d256a" width=360 />

2023-07-14 08:10 UTC, dsvensson commented
The alpha spam is only for func_laser as it changes alpha over time. The syscall could be updated to log once per map in a separate commit.

The server could support alpha as well :) should finish that.

2023-07-15 22:28 UTC, dsvensson commented
@inf1niti The ambient sounds in rctf package lack cue markers - they do have other types of markers that varies from file to file, but not the `ltxt`+`mark` that ezq looks for. fte is more relaxed and only looks for `mark`. hexdump any of them and compare with idSoftware ambience/*.wav, more info on https://quakewiki.org/wiki/ambientsound ... do they loop correctly in other engines?

2023-07-15 23:35 UTC, dsvensson commented
The wav files can be modified with python or something to adhere to the ltxt+mark way, and a future improvement to ezq would be to parse additional marker types in wav files to make it easier to work with audio tools from this century.

A workaround to verify that ambient_general does what it says it should is to add this to S_LoadSound:

```c
	if (loopstart == -1 && strncmp(s->name, "ambience/", 9) == 0) {
		loopstart = 0;
	}
```

at the end before resample.

2023-07-16 18:59 UTC, tcsabina requested changes

2023-07-17 07:35 UTC, dsvensson commented on include/progs.h
>  } gedict_t;
Don't expect so. It's all allocated up front during mod init and cmodel.c used to need a ton of waste mem to load some of the newer maps. I fixed that so there should be lots of headroom now. Would be nice with some bitflag indirection or something to wipe out that struct, but think it's fine. In practice I could have reused a lot more as they are per ent and most aren't used in the same ent, but readability would suffer by using weird names for things. Have tried to reuse as many already declared members where the name was close enough.

2023-07-17 07:44 UTC, dsvensson commented on include/q_shared.h
Yes. And also minor task of moving mvdsv into ezq repo :)

2023-07-28 19:47 UTC, dsvensson commented
The comments wrt ambient_general are resolved by passing the wav files through this[[1]](https://github.com/qw-ctf/ambiencefix) utility that takes a `timestamp` in float seconds, `input` file, and `output` file argument and rewrites the RIFF header to fit ezquake - and less strict engines, 

1. https://github.com/qw-ctf/ambiencefix

2023-07-31 21:17 UTC, tcsabina approved these changes

2023-07-31 21:17 UTC, merged