Added crhook hook style
QW-Group/ktx pull request #304
Opened 2023-07-18 18:14 UTC by SpookyScaryDev

Added crhook hookstyle as described by @inf1niti in #303 
At the moment, haste still affects throw speed when using crhook, as that was the original behaviour crhook was removed. I also changed the naming of the speed constants, since the speed for the new hook styles was called CR_THROW_SPEED.

2023-07-19 04:45 UTC, inf1niti requested changes
So I've tested this, and it all seems to work.  

If you guys have tested it as well, and are OK with the speed - I'm cool with merging this. 👍 

My only suggestion (besides the couple of inline comments left below) is that we no longer really need the `hook_fast` option - it was meant to be an option for people who didn't want to use the enhancements provided by the `hook_smooth` setting, but this hook is exactly the same (but faster).  

My suggestion would be to removing the existing `hook_fast` implementation entirely, and renaming `crhook` to `hook_fast`.  The `crhook` name honestly doesn't make sense, and this hook is faster than the existing fast hook anyways 😄 

That way, we can also keep the hook options to 3, which feels slightly more reasonable than 4.

2023-07-19 04:45 UTC, inf1niti commented on src/grapple.c
> +
might want to convert these to a series of `if` statements, keeping the ternary doesn't make a ton of sense anymore.

2023-07-19 04:45 UTC, inf1niti commented on src/commands.c
> +	{ "crhook", 					hookcrhook, 					0, 			CF_PLAYER | CF_MATCHLESS, 											CD_HOOKCRHOOK },
I know this was the original command for this hookstyle, but it makes it more difficult to find the various options if they're not following the same naming convention.  Lets stick with the `hook_` prefix for this as well.

2023-07-19 09:07 UTC, cbirkeland commented
@inf1niti
Sounds good! Agree with naming. 
Thank you @inf1niti and @SpookyScaryDev .

2023-07-21 21:15 UTC, tcsabina commented
@SpookyScaryDev,
let us know when ready to merge.

2023-07-31 21:18 UTC, tcsabina commented
> @tcsabina Will do. Hope to do testing of the different options with the ctf community this week.

Hi @SpookyScaryDev,
Have you had a chance to test this? Are we ready to merge?

Let me know...

2023-08-08 20:11 UTC, tcsabina commented
Guys,
Have you had some time to test this? Are we ready to merge?

Let me know...

2023-08-08 20:38 UTC, cbirkeland commented
@SpookyScaryDev  is on vacation until 11th. Hence no reply :) From CTF Admins point of view, we are good to merge if crhook is back like it used to be before it got removed with the values we requested.
There was a night of testing but i think main focus was on the ctf bots that hiipe is working on.
Again, thanks!

2023-08-10 20:16 UTC, tcsabina commented
Thanks @cbirkeland!
Let's wait a few more days...

2023-08-14 17:52 UTC, SpookyScaryDev commented
If the code is ok, this should be ready to push now.

2023-08-14 21:31 UTC, merged

2023-08-14 21:32 UTC, tcsabina commented
> If the code is ok, this should be ready to push now.

Thanks for the note. Merged...